export const LISTA_PRECIO_LIST_REQUEST = 'LISTA_PRECIO_LIST_REQUEST';
export const LISTA_PRECIO_LIST_SUCCESS = 'LISTA_PRECIO_LIST_SUCCESS';
export const LISTA_PRECIO_LIST_FAIL = 'LISTA_PRECIO_LIST_FAIL';

export const LISTA_PRECIO_CREATE_REQUEST = 'LISTA_PRECIO_CREATE_REQUEST';
export const LISTA_PRECIO_CREATE_SUCCESS = 'LISTA_PRECIO_CREATE_SUCCESS';
export const LISTA_PRECIO_CREATE_FAIL = 'LISTA_PRECIO_CREATE_FAIL';