export const MARCA_CREATE_REQUEST = 'MARCA_CREATE_REQUEST';
export const MARCA_CREATE_SUCCESS = 'MARCA_CREATE_SUCCESS';
export const MARCA_CREATE_FAIL = 'MARCA_CREATE_FAIL';

export const MARCA_LIST_REQUEST = 'MARCA_LIST_REQUEST';
export const MARCA_LIST_SUCCESS = 'MARCA_LIST_SUCCESS';
export const MARCA_LIST_FAIL = 'MARCA_LIST_FAIL';

export const TOPMARCAS_LIST_REQUEST = 'TOPMARCAS_LIST_REQUEST';
export const TOPMARCAS_LIST_SUCCESS = 'TOPMARCAS_LIST_SUCCESS';
export const TOPMARCAS_LIST_FAIL = 'TOPMARCAS_LIST_FAIL';

export const MARCA_DETAILS_REQUEST = 'MARCA_DETAILS_REQUEST';
export const MARCA_DETAILS_SUCCESS = 'MARCA_DETAILS_SUCCESS';
export const MARCA_DETAILS_FAIL = 'MARCA_DETAILS_FAIL';
export const MARCA_DETAILS_RESET = 'MARCA_DETAILS_RESET';

export const MARCA_REVIEW_CREATE_REQUEST = 'MARCA_REVIEW_CREATE_REQUEST';
export const MARCA_REVIEW_CREATE_SUCCESS = 'MARCA_REVIEW_CREATE_SUCCESS';
export const MARCA_REVIEW_CREATE_FAIL = 'MARCA_REVIEW_CREATE_FAIL';
export const MARCA_REVIEW_CREATE_RESET = 'MARCA_REVIEW_CREATE_RESET';

//Para listar reseñas 
export const MARCA_REVIEW_LIST_REQUEST = 'MARCA_REVIEW_LIST_REQUEST';
export const MARCA_REVIEW_LIST_SUCCESS = 'MARCA_REVIEW_LIST_SUCCESS';
export const MARCA_REVIEW_LIST_FAIL = 'MARCA_REVIEW_LIST_FAIL';