export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const LISTAR_PRODUCTO_REQUEST = 'LISTAR_PRODUCTO_REQUEST';
export const LISTAR_PRODUCTO_SUCCESS = 'LISTAR_PRODUCTO_SUCCESS';
export const LISTAR_PRODUCTO_FAIL = 'LISTAR_PRODUCTO_FAIL';

export const LISTAR_UN_PRODUCTO_REQUEST = 'LISTAR_UN_PRODUCTO_REQUEST';
export const LISTAR_UN_PRODUCTO_SUCCESS = 'LISTAR_UN_PRODUCTO_SUCCESS';
export const LISTAR_UN_PRODUCTO_FAIL = 'LISTAR_UN_PRODUCTO_FAIL';

// Listar productos por marca
export const LISTAR_PRODUCTOS_MARCA_REQUEST = 'LISTAR_PRODUCTOS_MARCA_REQUEST';
export const LISTAR_PRODUCTOS_MARCA_SUCCESS = 'LISTAR_PRODUCTOS_MARCA_SUCCESS';
export const LISTAR_PRODUCTOS_MARCA_FAIL = 'LISTAR_PRODUCTOS_MARCA_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

//Constantes para eliminar productos
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

//Constantes para listar productos por categoría
export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

//Constantes para listar productos por Sub Categorías
export const PRODUCT_SUB_CATEGORY_LIST_REQUEST = 'PRODUCT_SUB_CATEGORY_LIST_REQUEST';
export const PRODUCT_SUB_CATEGORY_LIST_SUCCESS = 'PRODUCT_SUB_CATEGORY_LIST_SUCCESS';
export const PRODUCT_SUB_CATEGORY_LIST_FAIL = 'PRODUCT_SUB_CATEGORY_LIST_FAIL';

//Constantes para crear reseñas
export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';

//Para listar reseñas 
export const PRODUCTO_REVIEW_LIST_REQUEST = 'PRODUCTO_REVIEW_LIST_REQUEST';
export const PRODUCTO_REVIEW_LIST_SUCCESS = 'PRODUCTO_REVIEW_LIST_SUCCESS';
export const PRODUCTO_REVIEW_LIST_FAIL = 'PRODUCTO_REVIEW_LIST_FAIL';

// Listar productos por marca 2
export const LISTAR_PRODUCTOS_MARCA_2_REQUEST = 'LISTAR_PRODUCTOS_MARCA_2_REQUEST';
export const LISTAR_PRODUCTOS_MARCA_2_SUCCESS = 'LISTAR_PRODUCTOS_MARCA_2_SUCCESS';
export const LISTAR_PRODUCTOS_MARCA_2_FAIL = 'LISTAR_PRODUCTOS_MARCA_2_FAIL';